### ISSUE TITLE
Exclude a repository from the list if there are 0 issues with label `good-first-issues`

### ISSUE THREAD

**Issue by gomzyakov** [good-first-issues/good-first-issues.github.io#114]

**Comment by joshhazelhurst123** [comment]
Hi @gomzyakov I was just taking a look at this and I thought it was interesting and I might be able to assist.
- My understanding is that on /Generator.php line 42 or before there could a condition that tests if there is an issue >0 with the label good first issue. 
- I was looking at this part below in the REST API.  
- https://docs.github.com/en/rest/issues/labels?apiVersion=2022-11-28 [Get a label](https://docs.github.com/en/rest/issues/labels?apiVersion=2022-11-28#get-a-label)

I am just trying to piece this together, does this sound like I am on the right track? 
Thanks.

**Comment by gomzyakov** [comment]
@joshhazelhurst123 Hello!

Yes, you are on the right track!

**Comment by joshhazelhurst123** [comment]
Okay so based on what the API tells me here.
-  https://docs.github.com/en/search-github/searching-on-github/searching-for-repositories#search-based-on-number-of-issues-with-good-first-issue-or-help-wanted-labels

I can search based on number of issues with good first issue or help wanted labels. Below I have a condition that searches for good first issues that have the label 'good-first-issue' occurring 2 times or more. 
- https://github.com/search?utf8=%E2%9C%93&q=good-first-issues%3A>2&type=repositories

I can search for 'good-first-issue' to occur 0 times or more
- https://github.com/search?utf8=%E2%9C%93&q=good-first-issues%3A>0&type=repositories

So to run a search where there are 0 issues with the label 'good-first-issue' I would search like below. 
- https://github.com/search?utf8=%E2%9C%93&q=good-first-issues%3A<1&type=repositories

Which return 138m results. 

Pseudocode would be, create a function that searches through the repositories to see if there is >1 'good-first-issue' then put that into a list, array, basically store that list. Then have another list that searches through the repositories that looks to see if there is <1 'good-first-issue' then discard those repositories. 
So I basically have no idea how to code this, any tips would really help.

**Comment by gomzyakov** [comment]
@joshhazelhurst123 

Thanks for the excellent research work!

Based on your link:

https://docs.github.com/en/search-github/searching-on-github/searching-for-repositories#search-based-on-number-of-issues-with-good-first-issue-or-help-wanted-labels

I looked at the API documentation:

https://docs.github.com/en/rest/search/search?apiVersion=2022-11-28#search-repositories

After that I thought: Maybe we should give up the [repositories.json](https://github.com/gomzyakov/good-first-issue/blob/main/repositories.json) file?

You can simply take repositories from the API that have more than 2 labels `good first issues` and show them.

You can think in this direction and make a PR, or I will do this in a couple of weeks, and you will review my edits ;)

**Comment by joshhazelhurst123** [comment]
Hi @gomzyakov thanks for reviewing what I have done and taking at look at the research that I put forward as shown above. Yes, I think giving up on the respositories.json file is a good idea. I got a bit confused with how to piece this together and code it. 
- I like what you have written here. "You can simply take repositories from the API that have more than 2 labels good first issues and show them." Based on what I have posted here. Reference below

[joshhazelhurst123](https://github.com/joshhazelhurst123) commented [last week](https://github.com/good-first-issues/good-first-issues.github.io/issues/114#issuecomment-2132179312)
- I can search based on number of issues with good first issue or help wanted labels. Below I have a condition that searches for good first issues that have the label 'good-first-issue' occurring 2 times or more.

- [https://github.com/search?utf8=%E2%9C%93&q=good-first-issues%3A>2&type=repositories](https://github.com/search?utf8=%E2%9C%93&q=good-first-issues%3A%3E2&type=repositories)

-------------------------
[gomzyakov](https://github.com/gomzyakov) commented [4 hours ago](https://github.com/good-first-issues/good-first-issues.github.io/issues/114#issuecomment-2148971515)
- "You can think in this direction and make a PR, or I will do this in a couple of weeks, and you will review my edits".

I would like to do a PR and code this, I am still quite unsure how to code this and put it all together. I think the logical place to put this function is in 
- https://github.com/good-first-issues.github.io/tree/main/src/Renderer.php 
And, AND OR
- https://github.com/good-first-issues/good-first-issues.github.io/tree/main/src/Generator.php

------------------------

Thanks @gomzyakov hope that makes sense. If you can you guide me on how to code this I will do a PR with you or I am happy to wait to see what you will add in a couple of weeks.

**Comment by gomzyakov** [comment]
@joshhazelhurst123 Hi!

I implemented the idea described above in PR https://github.com/good-first-issues/good-first-issues.github.io/pull/188

At the basic level, everything works, but periodically there is a problem with exhausting the GitHub API limits.


But, that's a completely different task (you can [think about it](https://github.com/good-first-issues/good-first-issues.github.io/actions/runs/10472613129/job/29002610055) if you have time). I think the current task can be closed)

**Comment by gomzyakov** [comment]
**NOTE**: _This repository is no longer supported or updated by @gomzyakov . If you wish to continue to develop this code yourself, we recommend you fork it._
