### ISSUE TITLE
Add the warning "This file has been translated automatically" to all translation files

### ISSUE THREAD

**Issue by gomzyakov** [good-first-issues/good-first-issues.github.io#115]
Add the warning "This file has been translated automatically. If you find an error, just make a PR with the edits" to all translation files.

**Comment by joshhazelhurst123** [comment]
Would that be like a javascript error, such as a popup error? 
https://www.w3schools.com/js/js_popup.asp

**Comment by gomzyakov** [comment]
@joshhazelhurst123 

No, it should just be a quote like:

```md
>**NOTE:** _This file has been translated automatically. If you find an error, just make a PR with the edits" to all translation files._

```

Which will look something like:

>**NOTE:** _This file has been translated automatically. If you find an error, just make a PR with the edits" to all translation files._

**Comment by joshhazelhurst123** [comment]
ok thanks @gomzyakov 
So I think all of the translation files need the note you have just mentioned above "NOTE: This file has been translated automatically. If you find an error, just make a PR with the edits" to all translation files." then added to the end of file, at the bottom, or perhaps at the top of the page?

**Comment by gomzyakov** [comment]
@joshhazelhurst123 

I think it would be better at the top of the page)

**Comment by joshhazelhurst123** [comment]
Here is the updates, let me know what you think @gomzyakov
