### ISSUE TITLE
Fix language-links

### ISSUE THREAD

**Issue by gomzyakov** [good-first-issues/good-first-issues.github.io#193]
Like https://good-first-issues.github.io/lang/lang/Python.html

**Comment by gomzyakov** [comment]
**NOTE**: _This repository is no longer supported or updated by @gomzyakov . If you wish to continue to develop this code yourself, we recommend you fork it._

**Comment by ElephantRohck** [comment]
if you are talking about the below language links I can take it up

<img width="1055" alt="image" src="https://github.com/user-attachments/assets/7703636b-e0fd-400b-b212-ebd99bf63585">

**Comment by gomzyakov** [comment]
@ElephantRohck 


No, I wrote about URL-part `/lang/lang/` in links like https://good-first-issues.github.io/lang/lang/Python.html on a site https://good-first-issues.github.io

**Comment by ElephantRohck** [comment]
Hi @gomzyakov,

This https://good-first-issues.github.io/lang/lang/Python.html link is not working got it. 
But which file do you want me to update or make the correction.

can you please provide some more insight into it.
