### ISSUE TITLE
Update all translations of README.md

### ISSUE THREAD

**Issue by gomzyakov** [good-first-issues/good-first-issues.github.io#195]

**Comment by gomzyakov** [comment]
**NOTE**: _This repository is no longer supported or updated by @gomzyakov . If you wish to continue to develop this code yourself, we recommend you fork it._

**Comment by gomzyakov** [comment]
**NOTE**: _This repository is no longer supported or updated by @gomzyakov . If you wish to continue to develop this code yourself, we recommend you fork it._

**Comment by ElephantRohck** [comment]
hi are you talking about the attached translations ??

<img width="1055" alt="image" src="https://github.com/user-attachments/assets/045f2829-2d43-4473-bd12-eae3ede1ea7f">

**Comment by ElephantRohck** [comment]
I can take it up if you want ??

**Comment by gomzyakov** [comment]
@ElephantRohck Hi!

Yes, these are the files that are meant. If you have time and opportunity, you can bring the translations into line with https://github.com/good-first-issues/good-first-issues.github.io/blob/main/README.md

**Comment by ElephantRohck** [comment]
Hi @gomzyakov,

Please review.

**Comment by ElephantRohck** [comment]
@gomzyakov please review and let me know if it's fine or not

**Comment by gomzyakov** [comment]
@ElephantRohck 

This does not mean updating the titles of links to English, but updating the files with translations themselves, updating them.
