### ISSUE TITLE
Replace favicons on the site

### ISSUE THREAD

**Issue by gomzyakov** [good-first-issues/good-first-issues.github.io#48]

**Comment by draunger** [comment]
I want to solve this issue please assign me this

**Comment by gomzyakov** [comment]
@draunger Hello!

I'm sorry, favicons have already been added, but they need to be changed.

I renamed the task.

You can use the `social-preview.png` file from https://github.com/good-first-issues/good-first-issues.github.io/tree/main/assets/github to update favicons.

**Comment by gomzyakov** [comment]
Done in https://github.com/good-first-issues/good-first-issues.github.io/pull/52 by @lehuuphuocct123
