### ISSUE TITLE
Write article on Habr

### ISSUE THREAD

**Issue by gomzyakov** [good-first-issues/good-first-issues.github.io#6]

**Comment by OnyxHound** [comment]
Hey there! Is this issue still open? Could you give me more specific details on how you long you want/structured the article to be?

**Comment by gomzyakov** [comment]
@OnyxHound Hello!

Thank you for your desire to help, but I will write this article myself when I have time :)

**Comment by gomzyakov** [comment]
**NOTE**: _This repository is no longer supported or updated by @gomzyakov . If you wish to continue to develop this code yourself, we recommend you fork it._
