### ISSUE TITLE
Write post on Reddit

### ISSUE THREAD

**Issue by gomzyakov** [good-first-issues/good-first-issues.github.io#66]
Like https://www.reddit.com/r/golang/comments/16iay5q/looking_for_beginner_friendly_open_source_project/

**Comment by 0somesh** [comment]
Done

**Comment by SyedAbdullahIjazShah** [comment]
can i like it too?

**Comment by gomzyakov** [comment]
@SyedAbdullahIjazShah Hello!

Yes, of course, but it's too early)

I'll rewrite some of the functionality soon, after which we can think about publishing it on Reddit.

I'll let you know as soon as I'm done ;)

**Comment by SyedAbdullahIjazShah** [comment]
@gomzyakov sure

**Comment by gomzyakov** [comment]
**NOTE**: _This repository is no longer supported or updated by @gomzyakov . If you wish to continue to develop this code yourself, we recommend you fork it._
