### ISSUE TITLE
Add a favicon file in SVG format or 120x120 pixels

### ISSUE THREAD

**Issue by gomzyakov** [good-first-issues/good-first-issues.github.io#67]
```
Рекомендуем добавить на сайт https://good-first-issues.github.io/ файл favicon в формате SVG или размером 120×120 пикселей.

Favicon — это небольшая картинка, которая отображается в [сниппете](https://yandex.ru/support/webmaster/search-results/site-description.html) в результатах поиска Яндекса, рядом с адресом сайта в строке браузера, около названия сайта в Избранном или в Закладках браузера.
```

**Comment by akshitchowdhury** [comment]
Я был бы рад помочь вам.

**Comment by gomzyakov** [comment]
> Я был бы рад помочь вам.

@akshitchowdhury Супер) В качестве фавиконки можно взять иконку репозитория и ресайзить ее под нужные размеры.

**Comment by akshitchowdhury** [comment]
Конечно... Я буду держать вас в курсе этого. спасибо, что позволили мне над этим поработать👍

**Comment by akshitchowdhury** [comment]
@gomzyakov Как мне назначить это себе? Можете ли вы поручить эту проблему мне?

**Comment by gomzyakov** [comment]
@akshitchowdhury 

Я назначил эту ищуйку на вас 😉

**Comment by akshitchowdhury** [comment]
@gomzyakov Спасибо, приятель 👍 Когда ты хочешь, чтобы это было готово?

**Comment by gomzyakov** [comment]
**NOTE**: _This repository is no longer supported or updated by @gomzyakov . If you wish to continue to develop this code yourself, we recommend you fork it._
