### ISSUE TITLE
Broken link to HERO-images in all `README.md` files

### ISSUE THREAD

**Issue by gomzyakov** [good-first-issues/good-first-issues.github.io#91]
Loke this:

<img width="809" alt="image" src="https://github.com/good-first-issues/good-first-issues.github.io/assets/1460709/7a4c88f3-d367-4889-8933-6c301901be96">

**Comment by HyMike** [comment]
hi, I would love to work on this issue. Can you please assign it to me. thank you

**Comment by gomzyakov** [comment]
@HyMike Hello!

@Krishna01work has already made edits within https://github.com/good-first-issues/good-first-issues.github.io/pull/92
