### ISSUE TITLE
Check Russian translation of file `README.ru.md`

### ISSUE THREAD

**Issue by gomzyakov** [good-first-issues/good-first-issues.github.io#97]
https://github.com/good-first-issues/good-first-issues.github.io/blob/main/translations/README.ru.md

**Comment by akshitchowdhury** [comment]
Ты можешь рассчитывать на меня

**Comment by saksham-jain177** [comment]
@gomzyakov It seems correct

**Comment by gomzyakov** [comment]
**NOTE**: _This repository is no longer supported or updated by @gomzyakov . If you wish to continue to develop this code yourself, we recommend you fork it._
